<?php

namespace App\Filament\Resources\FamilyResource\Pages;

use App\Filament\Resources\FamilyResource;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;

class CreateFamily extends CreateRecord
{
  protected ?string $heading="اسماء العائلات";
    protected static string $resource = FamilyResource::class;
    protected function mutateFormDataBeforeCreate(array $data): array
    {
      $data['nation']='ليبيا';
      $data['country_id']=1;
      return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }
}
