<?php

namespace App\Filament\Resources\FamilyResource\Pages;

use App\Filament\Resources\FamilyResource;
use Filament\Actions;
use Filament\Resources\Pages\EditRecord;

class EditFamily extends EditRecord
{
    protected static string $resource = FamilyResource::class;
  protected ?string $heading="تعديل اسماء العائلات";
    protected function getHeaderActions(): array
    {
        return [
            Actions\DeleteAction::make(),
        ];
    }
    protected function mutateFormDataBeforeSave(array $data): array
    {
      $data['nation']='ليبيا';
      $data['country_id']=1;
      return parent::mutateFormDataBeforeSave($data); // TODO: Change the autogenerated stub
    }
    protected function getRedirectUrl(): string
    {

        return $this->previousUrl;
    }
}
