<?php

namespace App\Filament\Resources\VictimResource\Pages;

use App\Filament\Resources\VictimResource;
use Filament\Actions;
use Filament\Resources\Pages\EditRecord;
use Illuminate\Contracts\Support\Htmlable;
use Illuminate\Support\Facades\Auth;

class EditVictim extends EditRecord
{
    protected static string $resource = VictimResource::class;
    public function getTitle(): string|Htmlable
    {
      return 'تعديل بيانات ضحية'; // TODO: Change the autogenerated stub
    }

  protected function mutateFormDataBeforeSave(array $data): array
  {
    if ($data['male']=='ذكر') $data['husband_id']=null;
    if ($data['male']=='أنثي') $data['wife_id']=null;
    $data['FullName']=$data['Name1'].' '.$data['Name2'].' '.$data['Name3'].' '.$data['Name4'];
    $data['user_id']=Auth::id();
    return parent::mutateFormDataBeforeSave($data); // TODO: Change the autogenerated stub
  }

  protected function getHeaderActions(): array
    {
        return [
            Actions\DeleteAction::make(),
        ];
    }
  protected function getRedirectUrl(): string
  {

    return $this->getResource()::getUrl('index');
  }
}
